version: '3'
services:
  live-id-generate-provider-1:
    container_name: live-id-generate-provider-1
    image: 'registry.baidubce.com/live-test/live-id-generate-provider-docker:1.0.1'
    ports:
      - "9094:9094"
    volumes:
      - /tmp/logs/live-id-generate-provider:/tmp/logs/live-id-generate-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=192.168.31.105
      - DUBBO_PORT_TO_REGISTRY=9094
      - DUBBO_PORT_TO_BIND=9094
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
